" Use neovim defaults
set nocompatible
set autoindent
set autoread
set backspace=start,indent,eol
set belloff=all
set encoding=utf-8
set hidden
set history=10000
set hlsearch
set incsearch
set nojoinspaces
set laststatus=2
set mouse=a
set ruler
set showcmd
set smarttab
set tabpagemax=50
set wildmenu
if v:version >= 900
    set wildoptions+=pum
endif

" More preferences
set nomodeline
set expandtab
set tabstop=4
set shiftwidth=4
set ignorecase
set smartcase
set splitright
set splitbelow
set number
set nowrap
set showmatch
set matchtime=1
set list
set listchars=trail:~,tab:>-
set completeopt-=preview
set completeopt+=menuone
let &stl = " %t%( %m%r%)%=%l/%L #%{winnr()} "

" <esc> mappings timeout after 5 ms
" Makes it so that hitting escape doesn't take forever to leave insert mode.
set ttimeoutlen=5

" Gui options
set guioptions-=rLt

" Enable cursor shapes
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"

" Use Q to execute q register (used to be Q-ex mode)
nnoremap Q @q

" Make <c-L> behave like in neovim
nnoremap <c-l> <cmd>nohl<cr><cmd>dif<cr><c-l>

" Make command mode have emacs-style keybindings
" <c-e> already works
cnoremap <c-a> <home>
cnoremap <c-f> <right>
cnoremap <c-b> <left>
cnoremap <m-b> <s-left>
cnoremap <m-f> <s-right>

" Use %% to abbreviate current directory
cnoreabbrev <expr> %% expand('%:h')

syntax on
filetype plugin indent on
